"""add: search, device, like

Revision ID: 68e009b661ed
Revises:
Create Date: 2026-01-29 19:43:58.885146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68e009b661ed"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_search",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("term", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "likes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("comments", sa.Column("post_id", sa.BigInteger(), nullable=False))
    op.alter_column("comments", "user_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_foreign_key(None, "comments", "post", ["post_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.alter_column("comments", "user_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("comments", "post_id")
    op.drop_table("likes")
    op.drop_table("users_search")
    op.drop_table("devices")
    # ### end Alembic commands ###
