"""add: posttag m2

Revision ID: ffbad2a141f3
Revises: ec2d41dc5ba5
Create Date: 2026-02-06 19:56:04.699190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffbad2a141f3"
down_revision: Union[str, Sequence[str], None] = "ec2d41dc5ba5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_searches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("term", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("users_search")
    op.add_column(
        "devices", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.add_column(
        "devices", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "updated_at")
    op.drop_column("devices", "created_at")
    op.create_table(
        "users_search",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("term", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_search_pkey")),
    )
    op.drop_table("user_searches")
    # ### end Alembic commands ###
